# Generated by Django 4.2.6 on 2023-10-25 01:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default='0')),
                ('client', models.CharField(max_length=100)),
            ],
            managers=[
                ('cart_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
            ],
            managers=[
                ('category_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('on_sale', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100)], default=0)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('category_id', models.ManyToManyField(related_name='categories', to='cart.category')),
            ],
            managers=[
                ('product_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('total_to_pay', models.FloatField(default='1')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.addcart')),
            ],
            managers=[
                ('order_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.category')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
            ],
            managers=[
                ('categoryproduct_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='addcart',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cart.product'),
        ),
    ]
