# Generated by Django 4.2.6 on 2023-10-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_category_name_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calc_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
