# Generated by Django 4.2.6 on 2023-10-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_addcart_total_price_addcart_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
